### ISSUE TITLE
Tidytube not stopping ads in firefox private windows

### ISSUE THREAD

**Issue by KayGee53** [kakajuro/tidytube#17]
Ads have started again today 29/09 on firefox private windows which were working yesterday.

**Comment by kakajuro** [comment]
Which ads have started again? Send a screenshot if possible. Remember tidytube doesn't block ads that play during video playback so if those ads have started playing again it might be caused by another extension. By default extensions don't run in private windows by default on firefox, so check this setting hasn't been altered mistakenly. 
<div>
    <img src="https://github.com/user-attachments/assets/e1b93e5a-821b-4201-b62c-d974a7efb2db" />
<div>

**Comment by KayGee53** [comment]
Thanks for your quick reply, for some reason, it's working again on Firefox Windows, I will try the linux version later and let you know. My settings were the same as your screenshot, allow for private windows and not allow for restricted sites.

**Comment by KayGee53** [comment]
Hi, I have found the the ads are only appearing on the Linux version of Firefox, not the Windows version, please see screenshots attached. 
![Screenshot_20240930_204324](https://github.com/user-attachments/assets/1c417fbe-cfe7-4944-9555-3a5ace0ed4d7)
![Screenshot_20240930_204550](https://github.com/user-attachments/assets/f1a8333a-33df-44d1-8a66-ceeae3db31d9)
![Screenshot_20240930_204749](https://github.com/user-attachments/assets/b7b63050-ee53-40d6-b077-2916f88c5772)
Any help or comments appreciated.

**Comment by kakajuro** [comment]
Hi there. Unfortunately I don't have a linux machine to test on but I did do some testing on my windows machine. With the same settings I tried on my windows machine in private windows and I still got ads such as the ones you displayed in the screenshot. Tidytube isn't designed to block those kinds of ads and there are lots of other extensions that do that much better than I could implement it. I recommend using one of those other extensions alongside tidytube. Here are the only ads that tidytube blocks:

![image](https://github.com/user-attachments/assets/306118cf-0fe1-48da-9263-e6bc5f1e1ee9)
![image](https://github.com/user-attachments/assets/7bf52d77-80a9-4b93-8261-4c2f26c68562)

I think it could have been a coincidence that those ads were being blocked or it might have been due to another extension (assuming you have other content/ad blocking extensions installed). I know this doesn't exactly fix the problem but I hope this helped you understand the situation.

**Comment by KayGee53** [comment]
Thanks for that, not to worry, YouTube is overpowering with ads every few minutes during playback,  whatever about the ads at the start of videos. Thanks for your help 👍 Sent from my mobile
-------- Original message --------From: kakajuro ***@***.***> Date: 03/10/2024  21:36  (GMT+00:00) To: kakajuro/tidytube ***@***.***> Cc: KayGee53 ***@***.***>, Author ***@***.***> Subject: Re: [kakajuro/tidytube] Tidytube not stopping ads in firefox private windows (Issue #17) 
Hi there. Unfortunately I don't have a linux machine to test on but I did do some testing on my windows machine. With the same settings I tried on my windows machine in private windows and I still got ads such as the ones you displayed in the screenshot. Tidytube isn't designed to block those kinds of ads and there are lots of other extensions that do that much better than I could implement it. I recommend using one of those other extensions alongside tidytube. Here are the only ads that tidytube blocks:
image.png (view on web)
image.png (view on web)
I think it could have been a coincidence that those ads were being blocked or it might have been due to another extension (assuming you have other content/ad blocking extensions installed). I know this doesn't exactly fix the problem but I hope this helped you understand the situation.

**Comment by kakajuro** [comment]
No worries, glad the extension is helping you out regardless!

**Comment by KayGee53** [comment]
👍
